#!/bin/bash
# .openshift/action_hooks/build:

# gradle build
set -x

JAVA_VERSION=1.8.0
export JAVA_HOME=`find /usr/lib/jvm -name "$JAVA_VERSION"`
if [ -z JAVA_HOME ] ; then
  echo "INTENDED JAVA VERSION NOT FOUND!"
fi  

echo "Build"
DIR=`pwd`
cd $OPENSHIFT_REPO_DIR
export GRADLE_VERSION=2.13
export GRADLE_USER_HOME=${OPENSHIFT_DATA_DIR}gradle
export GRADLE_HOME=${OPENSHIFT_DATA_DIR}gradle-${GRADLE_VERSION}
export PATH=$GRADLE_HOME/bin:$PATH
if [ -f build.gradle ] ; then
  gradle --stacktrace -b build.gradle clean build
fi
cd $DIR
