#!/bin/bash
# .openshift/action_hooks/deploy:

set -x

echo "Deploying"
# Addition:
for i in `ls $OPENSHIFT_DATA_DIR/tomcat/webapps/*.war`; do
  dn=`basename $i .war`
  rm -rf $OPENSHIFT_DATA_DIR/tomcat/webapps/$dn
done
