#!/bin/bash
# .openshift/action_hooks/start:
set -x

echo "Start"
JAVA_VERSION=1.8.0
export JAVA_HOME=`find /usr/lib/jvm -name "$JAVA_VERSION"`
if [ -z JAVA_HOME ] ; then
  echo "INTENDED JAVA VERSION NOT FOUND!"
fi  
cd $OPENSHIFT_DATA_DIR/tomcat
bin/startup.sh

